baseURL = "https://movies.vev.su/"
title = "Фильмы"
defaultContentLanguage = "ru"
languageCode = "ru-ru"
publishdir = "./docs"

[params]
  subtitle = "Подборки кино"
  description = "Советуем, что и как смотреть"
  googleTagManagerId = "GTM-M5HZVHN"
  storageMedia = "https://ams.su"
#  storageMedia = "http://ams:1351"
